/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-03-08 05:31:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.shiro.subject.Subject;
import org.apache.shiro.SecurityUtils;
import com.gxhy.base.model.UserModel;
import com.gxhy.utils.AdcdUtil;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/common/base/include_BaseCommon.jsp", Long.valueOf(1551332213867L));
    _jspx_dependants.put("/common/base/taglibs_logout.jsp", Long.valueOf(1550805552674L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxhy.utils.AdcdUtil");
    _jspx_imports_classes.add("com.gxhy.base.model.UserModel");
    _jspx_imports_classes.add("org.apache.shiro.subject.Subject");
    _jspx_imports_classes.add("org.apache.shiro.SecurityUtils");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String appPath = request.getScheme() + "://"+ request.getServerName() + ":" + request.getServerPort();
	pageContext.setAttribute("appPath", appPath);
    pageContext.setAttribute("basePath", request.getContextPath()+"/");
    UserModel user = (UserModel)request.getSession().getAttribute("user");
    if(user !=null && user.getUserId() != null){
		  pageContext.setAttribute("userAdcd", user.getUserAddvcd());
  		  pageContext.setAttribute("username", user.getUserName());
  		  pageContext.setAttribute("userId", user.getUserId());
  		  if(user.getUserAddvcd() != null && user.getUserAddvcd() != ""){  			  
  		  	 //pageContext.setAttribute("adcdLevl", AdcdUtil.getRegionLevel(user.getUserAddvcd()));
  		  }
//   		  if(user.getRoles() != null){  			  
//    		  	 pageContext.setAttribute("roleId", user.getRoles().get(0).getRoleId());
//    		  }
    }else{
    	 Subject currentUser = SecurityUtils.getSubject();
    	 currentUser.getSession().removeAttribute("user");
    	 currentUser.getSession().removeAttribute("username");
    	 currentUser.getSession().removeAttribute("userId");
    	 request.getSession().removeAttribute("user");
    }

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<!-- 此公共JSP中存放系统中所有界面可能用得到的插件。个体单用的界面使用插件不要放在此处 -->\r\n");
      out.write("\t<!-- CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"common/util/bootstrap/css/bootstrap.min.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/layui/css/layui.css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zTree_v3/css/metroStyle/metroStyle.css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/css/layUtil.css\" >\r\n");
      out.write("\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/easyui/themes/metro-blue/easyui.css\">\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/easyui/themes/icon.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/lightBox/zoomify.min.css\"  />\r\n");
      out.write("\t\r\n");
      out.write("   <!-- 表格 -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrap/css/bootstrap-table.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/css/base_modal.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/css/base_table.css\">\r\n");
      out.write("\t<!-- JS -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://webapi.amap.com/maps?v=1.4.3&key=832085f1e357efae7eb7e34449ac1a36\"></script> \r\n");
      out.write("\t<script src=\"http://webapi.amap.com/ui/1.0/main.js?v=1.0.11\"></script>\r\n");
      out.write("\t<script  src=\"http://api.tianditu.com/api?v=4.0&tk=ecf2c200ad3310de9b5adbcaca144c66\"></script>\t \r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/jquery/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/jquery/jquery-latest.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/jquery/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/laydate/laydate.js\"></script>\r\n");
      out.write("\t<script  src=\"");
      out.print(request.getContextPath());
      out.write("/common/layui/layui.js\"></script>\r\n");
      out.write("\t<script  src=\"");
      out.print(request.getContextPath());
      out.write("/common/echarts/echarts.min.js\"></script>\r\n");
      out.write("\t<script  src=\"");
      out.print(request.getContextPath());
      out.write("/common/dateUtil/formatterDateUtils.js\"></script>\r\n");
      out.write("\t<script  src=\"");
      out.print(request.getContextPath());
      out.write("/common/dateUtil/formatterTipUtils.js\"></script>\r\n");
      out.write("\t<!-- ztree插件 -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/common/zTree_v3/js/jquery.ztree.core-3.5.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/common/zTree_v3/js/jquery.ztree.excheck-3.5.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/common/zTree_v3/js/jquery.ztree.exhide-3.5.min.js\" ></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/common/lightBox/zoomify.min.js\"></script>\t\r\n");
      out.write("\t<script src=\"https://open.ys7.com/sdk/js/1.3/ezuikit.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/common/My97DatePicker/WdatePicker.js\"></script>  \r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 表格 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrap/js/bootstrap-table.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrap/js/bootstrap-table-zh-CN.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrap/js/bootstrap-table-filter-control.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrap/js/tableExport.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrap/js/bootstrap-table-export.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrap/js/bootstrap-table-toolbar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 公共js -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/commonUtils.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!--  <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/tree.js\"></script> --->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/bootstrapTable.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/util/form.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no,minimal-ui\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("common/css/header.css\" >\r\n");
      out.write("\t<link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"bookmark\" href=\"images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("common/js/header.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("common/util/rem.js\"></script>\r\n");
      out.write("\t<title>河（湖）长制管理信息化系统</title>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t    var  userId='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar username = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar WEB_ROOT = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar adcd = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userAdcd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar nowClientWidth;//当前屏幕宽度\r\n");
      out.write("\t\tvar imgPath = \"D:/rcxh/file/\";\r\n");
      out.write("\t \t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body\" class=\"body\" style=\"overflow: hidden;\">\r\n");
      out.write("\t<header class=\"header\"  style=\"z-index:999;padding: 0px 0px;\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/base/header.jsp", out, false);
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\t<div id=\"loadurl\">\r\n");
      out.write("\t  <div class=\"layui-side layui-bg-black\">\r\n");
      out.write("\t    <div class=\"layui-side-scroll\">\r\n");
      out.write("\t\t\t <ul class=\"layui-nav layui-nav-tree site-demo-nav\" id=\"menuLeft-ul\"></ul>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"contract\">\r\n");
      out.write("\t        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("common/images/leftMenu/hide.png\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\t  \r\n");
      out.write("\t  <div id=\"conter-div-info\" data-per=\"\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
